### ISSUE TITLE
Can you please update the Maven repo to include bug fix?

### ISSUE THREAD

**Issue by iaraknes** [biojava/biojava#236]
There is a bug in biojava3-core version 3.1.0 that seems to have been fixed in the master branch, but an updated version does not yet reside in the Maven repo. Since biojava3-core in the Maven repo hasn't been updated since August I am wondering if you could please update the repo so that it will no longer be necessary to depend on a local snapshot release?

Below is a stacktrace caused by the bug in question:

~~~
Exception in thread "main" java.lang.ExceptionInInitializerError
< stack from my code >
Caused by: java.lang.NullPointerException
        at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
        at java.util.Collections$UnmodifiableList.<init>(Collections.java:1302)
        at java.util.Collections.unmodifiableList(Collections.java:1287)
        at org.biojava3.core.sequence.location.template.AbstractLocation.<init>(AbstractLocation.java:111)
        at org.biojava3.core.sequence.location.template.AbstractLocation.<init>(AbstractLocation.java:85)
        at org.biojava3.core.sequence.location.SimpleLocation.<init>(SimpleLocation.java:57)
        at org.biojava3.core.sequence.location.SimpleLocation.<init>(SimpleLocation.java:53)
        at org.biojava3.core.sequence.location.template.Location.<clinit>(Location.java:48)
        ... 10 more
~~~

I believe that [this commit](https://github.com/biojava/biojava/commit/48d425eadfa9c63c121e48e4fd86ec742d3388b2#diff-355f51589ee83f63016d922edc3594ca) is what fixed the issue (you can see that the constructor in the stack-trace no longer relies on the static variable). The patch is older than version 3.1.0, but I don't see the updated code in IntelliJ when i analyze the stacktrace.

**Comment by sbliven** [comment]
@iaraknes Development on 4.0.0 and 3.1.0 were concurrent, and the Java 8 patch didn't get backported to the 3.1.0 branch. I'd like to be better about backporting major bug fixes like that in the future, but as of now it would be difficult to do. We are quite close to a 4.0.0 release (nearly all 4.0.0 issues have been fixed, so 'close' should mean weeks to a month). Thanks for your patience!

**Comment by andreasprlic** [comment]
I think it is clear we need to make the new release available as soon as possible. I started #238 to keep track of what is missing at this stage.
