### ISSUE TITLE
CompoundNotFoundException: Compound W not found

### ISSUE THREAD

**Issue by ylzheng** [biojava/biojava#362]
Dear Sir or Madam,
When using biojava 4., I get the following error message.  Can you help put mixed base cases, R, Y, W, M, K, S, H, B, V, D, I in the nucleotide compound set?  

Exception in thread "main" org.biojava.nbio.core.exceptions.CompoundNotFoundException: Compound W not found
	at org.biojava.nbio.core.sequence.loader.StringProxySequenceReader.setContents(StringProxySequenceReader.java:77)
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReader.<init>(GenbankProxySequenceReader.java:86)

Thank you very much!

Yueli Zheng

**Comment by josemduarte** [comment]
You need to use an `AmbiguityCompoundSet`. 

For instance this works for me:

```java
DNASequence dna = new DNASequence("RYWMKSHBVD", AmbiguityDNACompoundSet.getDNACompoundSet());
		
RNASequence rna = new RNASequence("RYWMKSHBVD", AmbiguityRNACompoundSet.getRNACompoundSet());
		
System.out.println(dna);
	
System.out.println(rna);
```
