### ISSUE TITLE
Error parsing 1S32

### ISSUE THREAD

**Issue by abradle** [biojava/biojava#368]
I'm trying to parse a structure using the below code and the receiving the following exception. Any help would be gratefully received.

Best wishes,

Anthony
```
package org.trial.debug;

import java.io.IOException;
import org.biojava.nbio.structure.Structure;
import org.biojava.nbio.structure.StructureException;
import org.biojava.nbio.structure.align.util.AtomCache;

public class DebugBioJava {
	public static void main(String[] args) throws IOException, StructureException{
		String pdbId = "1S32";
		AtomCache cache = new AtomCache();
		Structure s = cache.getStructure(pdbId);
	}
}

```

```java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "."
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.buildObject(SimpleMMcifParser.java:1002)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.endLineChecks(SimpleMMcifParser.java:649)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.parse(SimpleMMcifParser.java:278)
	at org.biojava.nbio.structure.io.MMCIFFileReader.getStructure(MMCIFFileReader.java:111)
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getStructureById(LocalPDBDirectory.java:345)
	at org.biojava.nbio.structure.align.util.AtomCache.loadStructureFromCifByPdbId(AtomCache.java:1191)
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:386)
	at org.biojava.nbio.structure.StructureIO.getStructure(StructureIO.java:103)```

**Comment by abradle** [comment]
I'm using the latest commit of BioJava  1dca682b16c8271b76401bfe793ad0c139f46ac5

**Comment by josemduarte** [comment]
It looks like a problem in SimpleMMcifParser and an unusual file with a '.' value in an unusual place, I'll take a look.
