### ISSUE TITLE
EOFException: Unexpected end of ZLIB input stream (SimpleMMcifParser)

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#404]
I am getting an Exception when parsing some protein chains. They have to be rare cases, because I found only 9 cases from 30K chains I analyzed. From the Exception description it seems to be something wrong with the PDB file, but I do not know what can it be (I looked at the files and they look OK to me).

```java
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.7.0_95]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.7.0_95]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116) ~[?:1.7.0_95]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283) ~[?:1.7.0_95]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325) ~[?:1.7.0_95]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) ~[?:1.7.0_95]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.7.0_95]
	at java.io.BufferedReader.fill(BufferedReader.java:154) ~[?:1.7.0_95]
	at java.io.BufferedReader.readLine(BufferedReader.java:317) ~[?:1.7.0_95]
	at java.io.BufferedReader.readLine(BufferedReader.java:382) ~[?:1.7.0_95]
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.parse(SimpleMMcifParser.java:179) ~[classes/:?]
	at org.biojava.nbio.structure.io.MMCIFFileReader.getStructure(MMCIFFileReader.java:111) ~[classes/:?]
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getStructureById(LocalPDBDirectory.java:345) ~[classes/:?]
	at org.biojava.nbio.structure.align.util.AtomCache.loadStructureFromCifByPdbId(AtomCache.java:1038) ~[classes/:?]
	at org.biojava.nbio.structure.align.util.AtomCache.getStructureForPdbId(AtomCache.java:1019) ~[classes/:?]
	at org.biojava.nbio.structure.SubstructureIdentifier.loadStructure(SubstructureIdentifier.java:315) ~[classes/:?]
	at org.biojava.nbio.structure.align.client.StructureName.loadStructure(StructureName.java:349) ~[classes/:?]
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:394) ~[classes/:?]
	at demo.CeSymmMain$CeSymmWorker.run(CeSymmMain.java:1057) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
```

Cases where the Exception occurs: 4I43.B, 3JCL.A, 5FJ8 (chains A, B, O, P, M, I, Q).
To reproduce the Exception just try to load one of the structures above through **AtomCache**

**Comment by josemduarte** [comment]
I've tried the ids you report but I'm not getting the exception. I tried this:

```java
Structure s = StructureIO.getStructure("4I43.B");
```

Can it be that you have some corrupted files in your pdb cache locally?

**Comment by lafita** [comment]
Indeed, I had corrupted files in my PDBDIR. I removed them and now everything works fine! Thanks @josemduarte
