### ISSUE TITLE
NumberFormatException for Structures with Insertion Codes

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#515]
I encountered an Exception when trying to parse some structures, with something that seems related to insertion codes. The two I looked at are obsoleted, so it may be a problem in the file rather than a biojava bug. The two entries are **2bk7** and **1vs9**.

To reproduce it in biojava5, the following settings need to be applied to download the structure:

```java
AtomCache cache = new AtomCache();
cache.setUseMmCif(true);
cache.setObsoleteBehavior(ObsoleteBehavior.FETCH_OBSOLETE);
Structure s = cache.getStructure(name);
```

The Exception thrown:

<pre>
Exception in thread "main" java.lang.NumberFormatException: For input string: "137A"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifConsumer.newAtomSite(SimpleMMcifConsumer.java:341)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.triggerNewAtomSite(SimpleMMcifParser.java:1083)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.endLineChecks(SimpleMMcifParser.java:634)
	at org.biojava.nbio.structure.io.mmcif.SimpleMMcifParser.parse(SimpleMMcifParser.java:321)
	at org.biojava.nbio.structure.io.MMCIFFileReader.getStructure(MMCIFFileReader.java:111)
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getStructureById(LocalPDBDirectory.java:345)
	at org.biojava.nbio.structure.align.util.AtomCache.loadStructureFromCifByPdbId(AtomCache.java:1048)
	at org.biojava.nbio.structure.align.util.AtomCache.getStructureForPdbId(AtomCache.java:1020)
	at org.biojava.nbio.structure.SubstructureIdentifier.loadStructure(SubstructureIdentifier.java:316)
	at org.biojava.nbio.structure.align.client.StructureName.loadStructure(StructureName.java:549)
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:527)
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:511)
</pre>

**Comment by lafita** [comment]
The structures that superseded them do not throw any `Exception` for parsing, which means the problem was solved when they were obsoleted. However, it seems a common error, since it occurred a dozen of times when analyzing all the **CATH** domains.

**Comment by sbliven** [comment]
The problem is caused by including insertion codes in the `_atom_site.auth_seq_id` field (as well as a few linked fields like `_pdbx_poly_seq_scheme.pdb_seq_num`). The mmcif specification does technically allow letters and punctuation in this field, but all the current files I've checked keep it numeric and split the insertion code to `_atom_site.pdbx_PDB_ins_code`.

It seems reasonable to throw an exception here, but we could also pretty easily adapt the SimpleMMcifConsumer to tolerate this particular pattern. Opinions?

**Comment by josemduarte** [comment]
I wouldn't adapt the parser to cope with this... The best solution is catching the exception and producing some good error message.
