### ISSUE TITLE
java.lang.ExceptionInInitializerError in protein disorder module, JRonn

### ISSUE THREAD

**Issue by srikanthBezawada** [biojava/biojava#639]
Hi,

I get the following stack trace when I try to find disorder scores using
biojava protein disorder module. Can you please let me know the fix ?
I'm using Java8 and biojava-protein-disorder-4.1.0

Thanks!

```

Exception in thread "main" java.lang.ExceptionInInitializerError
at biojavausage.BioJavaUsage.main(BioJavaUsage.java:*25*)
Caused by: java.util.InputMismatchException
at java.util.Scanner.throwFor(Scanner.java:864)
at java.util.Scanner.next(Scanner.java:1485)
at java.util.Scanner.nextInt(Scanner.java:2117)
at java.util.Scanner.nextInt(Scanner.java:2076)
at org.biojava.nbio.ronn.ModelLoader.loadModels(ModelLoader.java:175)
at org.biojava.nbio.ronn.Jronn.<clinit>(Jronn.java:55)
... 1 more

```

_Here is the line *25* which is the same line from the test folder of
biojava github._

```
float[] rawProbabilityScores = Jronn.getDisorderScores(new
FastaSequence("name", "LLRGRHLMNGTMIMRPWNFLNDHHFPKFFPHLIEQQAIWLADWWRKKHC" +
"RPLPTRAPTMDQWDHFALIQKHWTANLWFLTFPFNDKWGWIWFLKDWTPGSADQAQRACTWFFCHGHDTN" +
"CQIIFEGRNAPERADPMWTGGLNKHIIARGHFFQSNKFHFLERKFCEMAEIERPNFTCRTLDCQKFPWDDP"
));
```

**Comment by josemduarte** [comment]
Did you try the latest version ([4.2.6](https://github.com/biojava/biojava/releases/tag/biojava-4.2.6))?

**Comment by srikanthBezawada** [comment]
Thanks @josemduarte , it's working with latest version 4.2.6
