### ISSUE TITLE
Potential error when reading non ACTG nucleotide

### ISSUE THREAD

**Issue by Gaussia** [biojava/biojava#787]
I am using biojava to parse genebank files
```
gbFile = GenbankReaderHelper.readGenbankDNASequence(new GZIPInputStream(new FileInputStream("GCF_000091665.1_ASM9166v1_genomic.gbff.gz")));
```
and I receive this error:
```
Exception in thread "main" org.biojava.nbio.core.exceptions.CompoundNotFoundException: Cannot find compound for: S
	at org.biojava.nbio.core.sequence.storage.ArrayListSequenceReader.setContents(ArrayListSequenceReader.java:206)
	at org.biojava.nbio.core.sequence.template.AbstractSequence.<init>(AbstractSequence.java:89)
	at org.biojava.nbio.core.sequence.DNASequence.<init>(DNASequence.java:84)
	at org.biojava.nbio.core.sequence.io.DNASequenceCreator.getSequence(DNASequenceCreator.java:64)
	at org.biojava.nbio.core.sequence.io.GenbankReader.process(GenbankReader.java:148)
	at org.biojava.nbio.core.sequence.io.GenbankReader.process(GenbankReader.java:111)
	at org.biojava.nbio.core.sequence.io.GenbankReaderHelper.readGenbankDNASequence(GenbankReaderHelper.java:147)
	at func.readGBFile(func.java:18)
	at makeDatabases.main(makeDatabases.java:36)
```
If I check the genbank file the genome sequence do contain a `s` nucleotide (stands for `c` or `g`). Could this be the cause of the error? If so, is there any way to deal with it?

**Comment by Gaussia** [comment]
Ok, turns out you can do it using genbankReader and 
```java
InputStream is = new FileInputStream(fileName); 
GenbankReader<DNASequence, NucleotideCompound> dnaReader = new GenbankReader<DNASequence, NucleotideCompound>(is, new GenericGenbankHeaderParser<DNASequence,NucleotideCompound>(),
		        new DNASequenceCreator(AmbiguityDNACompoundSet.getDNACompoundSet())
		        ); 
LinkedHashMap<String, DNASequence> gbFile = dnaReader.process();
is.close();
```
which should work. 
Cheers
