### ISSUE TITLE
HTTP 429 Too Many Requests returned from NCBI eutils

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava#837]
`GenbankProxySequenceReaderTest` may need to be modified to pause between requests to NCBI eutils, or `GenbankProxySequenceReader` updated to handle request rate limiting with retries.

```
$ mvn clean install
...
[INFO] Running org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest
12:42:52 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_000932.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000932.1&rettype=fasta&retmode=text
12:42:52 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_000932.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000932.1&rettype=fasta&retmode=text
12:42:53 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_000932.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000932.1&rettype=fasta&retmode=text
12:42:53 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_016912.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_016912.1&rettype=fasta&retmode=text
12:42:53 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_016912.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_016912.1&rettype=fasta&retmode=text
12:42:53 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_009648.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_009648.1&rettype=fasta&retmode=text
12:42:54 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_009648.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_009648.1&rettype=fasta&retmode=text
[ERROR] Tests run: 16, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 6.156 s <<< FAILURE! - in org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest
[ERROR] testProteinSequenceFactoring[2](org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest)  Time elapsed: 0.225 s  <<< ERROR!
java.lang.NullPointerException
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest.testProteinSequenceFactoring(GenbankProxySequenceReaderTest.java:183)

[ERROR] testFeatures[2](org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest)  Time elapsed: 0.168 s  <<< ERROR!
java.lang.NullPointerException
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest.testFeatures(GenbankProxySequenceReaderTest.java:133)

[ERROR] testProteinSequenceFactoring[5](org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest)  Time elapsed: 0.219 s  <<< ERROR!
java.lang.NullPointerException
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest.testProteinSequenceFactoring(GenbankProxySequenceReaderTest.java:183)

[ERROR] testFeatures[5](org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest)  Time elapsed: 0.231 s  <<< ERROR!
java.lang.NullPointerException
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest.testFeatures(GenbankProxySequenceReaderTest.java:133)
```

**Comment by josemduarte** [comment]
Actually I had introduced a pause between requests in ed7fb66cb1e450030e5e464770ed79c116a27d7d but it seems that it was removed in 11c9beb17f8a7c8f581ffa2b58fdf3e00250f1bd. @lee-mcfaul can you comment on why removing the pause between requests?

Note this issue was discussed already in #831

**Comment by josemduarte** [comment]
I re-introduced the delays in the test again so that the 429s stop. See 59e51fdc7920ec142f707bbe642c64905efa8994
