### ISSUE TITLE
make or read genbank file error when feature spans zero point of circular sequence

### ISSUE THREAD

**Issue by chenzhiw** [biojava/biojava#855]
Download a [genbank file](https://media.addgene.org/snapgene-media/v1.6.2-0-g4b4ed87/sequences/74/51/47451/addgene-plasmid-37845-sequence-47451.gbk) from [this page](http://www.addgene.org/37845/sequences/#depositor-full).
Read it  with biojava and error as below:

Exception in thread "main" java.lang.IllegalStateException: Start (7028) is greater than end (286); this is an incorrect format
	at org.biojava.nbio.core.sequence.location.template.AbstractLocation.assertLocation(AbstractLocation.java:133)
	at org.biojava.nbio.core.sequence.location.template.AbstractLocation.<init>(AbstractLocation.java:119)
	at org.biojava.nbio.core.sequence.location.template.AbstractLocation.<init>(AbstractLocation.java:92)
	at org.biojava.nbio.core.sequence.location.SimpleLocation.<init>(SimpleLocation.java:64)
	at org.biojava.nbio.core.sequence.location.SimpleLocation.<init>(SimpleLocation.java:55)
	at org.biojava.nbio.core.sequence.location.InsdcParser.parseLocationString(InsdcParser.java:241)
	at org.biojava.nbio.core.sequence.location.InsdcParser.parseLocationString(InsdcParser.java:189)
	at org.biojava.nbio.core.sequence.location.InsdcParser.parse(InsdcParser.java:143)
	at org.biojava.nbio.core.sequence.io.GenbankSequenceParser.parse(GenbankSequenceParser.java:283)
	at org.biojava.nbio.core.sequence.io.GenbankSequenceParser.getSequence(GenbankSequenceParser.java:402)
	at org.biojava.nbio.core.sequence.io.GenbankReader.process(GenbankReader.java:153)
	at org.biojava.nbio.core.sequence.io.GenbankReader.process(GenbankReader.java:121)
	at org.biojava.nbio.core.sequence.io.GenbankReaderHelper.readGenbankDNASequence(GenbankReaderHelper.java:178)
	at org.biojava.nbio.core.sequence.io.GenbankReaderHelper.readGenbankDNASequence(GenbankReaderHelper.java:190)

**Comment by chenzhiw** [comment]
error part as below:

     CDS             complement(7028..286)
                     /codon_start=1
                     /gene="bla"
                     /product="beta-lactamase"
                     /label=AmpR

**Comment by josemduarte** [comment]
Thanks for reporting.

So should the start<end check be removed completely? Any opinions?

**Comment by paolopavan** [comment]
I think that start<end check was a specification of the GB format. The location parser was implemented according to http://www.insdc.org/files/feature_table.html#3.4 and while I cannot find anymore the specifics that 3' end must be represented by a greater number that 5' it is clear from the documentation and examples that this is expected. 
Moreover, when you look at complement() definition in the Operators paragraph it is clear that a location is always expected as 5'-to-3' and 5' is the first base, I think it may be misleading and dangerous otherwise.
@chenzhiw how many documents you found which fail reading with this parser?

As a note, it is possible that the insdc document has been updated over time and has diverged slightly by the original implementation.

**Comment by chenzhiw** [comment]
@paolopavan Thanks for your replay. I also have read the specification and cannot find any word that 3' end must greater than 5'.
As we know, the vector dna is circular, the start point can be any base theoretically. How can we define the feature spans start point.
Snapgene write it like _7028..286_. I find an example on NCBI [AF169008.1](https://www.ncbi.nlm.nih.gov/nuccore/AF169008.1), the CDS region is _join(20747..21170,1..23)_.
I think we can accept the 7028..286 form compatibility.

**Comment by paolopavan** [comment]
Today there is not reference but the check is there since in the past this was mentioned. What in fact if I write 100..1 in linear chromosome context? Would you consider the forward or the reverse strand?
I think in fact that the form `complement(join(7028.. 7602,1.. 286))` that you correctly report would have been the intended form by NCBI and is much less ambigue. Even if in a circular chromosomes it may seem trivial, as far as I know the first base is related to the origin of replication.
I must say that this event does not surprise me a lot, it happens over time. That is why I asked you how many records you have found that break this rule and if it may be the case to spot it to the sourcing organization.
Unless an explicit format specification is found, this case should be closed in my opinion.

**Comment by sbliven** [comment]
I think we should allow 5'<3' for circular DNA but not for linear chromosomes. We can detect which type we have based on the LOCUS line.

Note that for circular chromosomes 100..1 is different from 1..100 and neither have anything to do with the reverse strand. Thus it makes sense to raise an error in linear chromosomes.

It would be good to have some tests relating to this issue.

**Comment by chenzhiw** [comment]
I agree with you @sbliven . Only for circular DNA.

**Comment by paolopavan** [comment]
Hello guys, opened a PR to address the issue. Want to have a look?

**Comment by paolopavan** [comment]
I also created a PR to commit a bit of code cleaning of the files touched. A lot of work more should be actually done in such a sense. I made a different PR to facilitate the review of the main one.

This code cleaning is not related to the new modifications and could be merged separately but actually is built on the top of the previous PR.

**Comment by paolopavan** [comment]
By the way, I may just miss some pieces or a different way to represent it, does AbstractSequence misses a kind of isCircular property? Would it be good to add?

**Comment by heuermh** [comment]
Fixed by #872
