### ISSUE TITLE
Empty entity list when parsing PDB ID 3FDJ source record

### ISSUE THREAD

**Issue by aalhossary** [biojava/biojava#932]
When I tried to parse 3FDJ, an IndexOutOfBoundsException is thrown in the pdb_SOURCE_Handler() function.

> Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.biojava.nbio.structure.io.PDBFileParser.sourceValueSetter(PDBFileParser.java:1255)
	at org.biojava.nbio.structure.io.PDBFileParser.pdb_SOURCE_Handler(PDBFileParser.java:1221)
	at org.biojava.nbio.structure.io.PDBFileParser.makeCompounds(PDBFileParser.java:2755)
	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2695)
	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2557)
	at org.biojava.nbio.structure.io.PDBFileReader.getStructure(PDBFileReader.java:140)

It seems to be more related to the entities rather than the SOURCE records.
Below is a bug generating code snippet.
```
	private static void demoAtomCache() {
		UserConfiguration userConfiguration = new UserConfiguration();
		userConfiguration.setFileFormat(UserConfiguration.PDB_FORMAT);
		AtomCache cache = new AtomCache(userConfiguration);

		try {
			Structure s = cache.getStructure("3fdj");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
```

**Comment by aalhossary** [comment]
I found the cause of the bug.
It is because the token '(ZVNW5VJFOAACMF8NLOPRFTMWH60:01:1-275)' contains a colon ':'.
I will fix it and create a PR.
