### ISSUE TITLE
NPE when parsing certain PDB structures with "params.setCreateAtomBonds(true)"

### ISSUE THREAD

**Issue by cleberecht** [biojava/biojava#943]
Hi,
thank you a lot providing and updating BioJava continuously.

I encountered a problem with the legacy pdb file parsing in the latest `6.0.0-alpha4` version of BioJava. When creating creating bonds an NPE is thrown.

Minimal (not)working example:
``` java
PDBFileReader reader = new PDBFileReader();
FileParsingParameters params = new FileParsingParameters();
params.setCreateAtomBonds(true);
reader.setFileParsingParameters(params);
reader.getStructureById("1v9i");
```
throws
```
java.lang.NullPointerException: Cannot invoke "org.biojava.nbio.structure.Chain.getGroupByPDB(org.biojava.nbio.structure.ResidueNumber)" because "chain" is null

	at org.biojava.nbio.structure.io.BondMaker.getAtomFromRecord(BondMaker.java:475)
	at org.biojava.nbio.structure.io.BondMaker.formLinkRecordBond(BondMaker.java:336)
	at org.biojava.nbio.structure.io.PDBFileParser.formBonds(PDBFileParser.java:2775)
	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2700)
	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2557)
	at org.biojava.nbio.structure.io.PDBFileReader.getStructure(PDBFileReader.java:140)
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getStructureById(LocalPDBDirectory.java:334)
	at ...
```
I think there is a problem with the legacy chain id format where `authId:C` is requested but only `asymId:A` and `asymId:B` are present.

All the Best
Christoph

**Comment by josemduarte** [comment]
Thanks for reporting @cleberecht . I'll see if I can work on a fix. As a general advice, PDB format is legacy and with time support for it will be degrading to the most basic parsing only. If you are dealing with deposited PDB files, please use mmCIF or BCIF.
